# name: Terraform Plan - Develop

# on:
#   push:
#     branches:
#       - develop
#   pull_request:
#     branches:
#       - develop

# jobs:
#   terraform-plan:
#     name: "Terraform Plan"
#     runs-on: ubuntu-latest
    
#     defaults:
#       run:
#         working-directory: ./code

#     env:
#       TF_VAR_vault_address: ${{ secrets.VAULT_ADDRESS }}
#       TF_VAR_vault_token: ${{ secrets.VAULT_TOKEN }}

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: "1.14.0"

#       - name: Terraform Init
#         id: init
#         run: terraform init


#       - name: Terraform Format Check
#         id: fmt
#         run: terraform fmt -check
#         continue-on-error: true
 

#       - name: Terraform Validate
#         id: validate
#         run: terraform validate

#       - name: Terraform Plan
#         id: plan
#         run: terraform plan -no-color -input=false
#         continue-on-error: false